version: '3.1'
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: webUser
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: masmovil
    volumes:
      - /var/www/mysqlDocker:/var/lib/mysql

  masmovil:
    depends_on:
      - "db"
    image: masmovil/masmovil
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masmovil
    ports:
      - 8000:8000